a= ("@@@@  @  @     @       @ @@@@ @@    @")
b= ("@     @  @      @     @  @    @ @   @")
c= ("@ @@  @  @       @   @   @@@@ @  @  @")
d= ("@  @  @  @        @ @    @    @   @ @")
e= ("@@@@  @  @@@@      @     @@@@ @     @ ")
print(a)
print(b)
print(c)
print(d)
print(e)
print ("i'm reading right now")
a1=  ('"aku main bulu tangkis"')
print (a1)